#!/usr/bin/env bash
# installer script


install_dotfiles() {
	cp dotfiles/bashrc.template dotfiles/bashrc

	shopt -s globstar
	for FILE in $PWD/dotfiles/**; do

		[[ $FILE =~ dotfiles/$ || $FILE =~ template ]] && continue
		local DIST_PATH="${FILE/setup\/dotfiles\//.}"

		[[ -d $FILE ]] && 
		{
			mkdir -p "$DIST_PATH"
			continue
		}
		
		# what if the link is not pointing where we wanted?
		[[ -e "$DIST_PATH" && -L "$DIST_PATH" ]] && continue
		[[ -e "$DIST_PATH" ]] && rm -ri "$DIST_PATH"

		ln -s "$FILE" "$DIST_PATH"

	done	
	shopt -u globstar
	unset FILE
}
install_dotfiles

# Install lib to global user library
sudo cp dotfiles/local/lib/* /usr/local/lib/


# Install custom files
install_custom_files() {
	for FILE in custom/*; do
		local DIST_PATH=$(awk 'NR==2 { print $NF}' "$FILE")
		[[ $FILE =~ ^/home ]] && 
		{
			cp "$FILE" "$DIST_PATH"
			continue
		}
		sudo cp "$FILE" "$DIST_PATH"

	done
	unset FILE
}
install_custom_files
