#!/usr/bin/env bash

log() {
	echo "[INFO] - " "$@"
}

warn() {
	echo "[WARNING] - " "$@" | tee /dev/stderr 
}

error() {
	echo "[ERROR] - " "$@" >&2 
}

unset_proxy() {
	unset PROXY_HOST PROXY_PORT HTTP_PROXY HTTPS_PROXY NO_PROXY
}

export_proxy() {
	export PROXY_PORT=${1:-8080}

	ping -c1 -W1 _gateway >/dev/null 2>&1 || {
		error "unable to reach gateway"
		return 1
	}

	</dev/tcp/_gateway/$PROXY_PORT || {
		error "port $PROXY_PORT is closed"
		return 1
	}

	export HTTP_PROXY="http://$PROXY_HOST:$PROXY_PORT"
	export HTTPS_PROXY="$HTTP_PROXY"
	export NO_PROXY="127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
}


# Proxy Managment
sysproxyctl() {
	kwriteconfig6 \
		--file /home/kalcodes/.config/kioslaverc \
		--group "Proxy Settings" "$@"
}

enable_system_proxy() {
	export_proxy
	sysproxyctl --key ProxyType 1
	sysproxyctl --key httpProxy "http://$PROXY_HOST $PROXY_PORT"
	sysproxyctl --key httpsProxy "http://$PROXY_HOST $PROXY_PORT"
	sysproxyctl --key NoProxyFor "$NO_PROXY"
}

disable_system_proxy() {
	unset_proxy
	sysproxyctl --key ProxyType 0
}

update_datetime() {

	</dev/tcp/_gateway/8123 && {
		TIME=$(nc -i1 _gateway 8123 2>/dev/null)
	}

	[[ -z $TIME ]] && {
		export_proxy
		API_DATA=$(curl -skL "https://timeapi.kalcodes.workers.dev/api")
		TIME=$(echo $API_DATA | jq -r .iso)
	}
	
	if [[ -n "$TIME" && "$TIME" != "null" ]]; then
		date -s "$TIME"
	fi
	unset TIME API_DATA
}

testdir () {
	local dir=~/.testdir/$1
	[[ -n $1 ]] && mkdir -p $dir cd "$dir"
}

# dotenv file toolkit (1 - file, 2 - key, 3 - value)
uenv () {
	sed -i $1 -e s/^$2/=$3/
}
