#!/usr/bin/env bash

if [[ -f $HOME/.local/lib/utils ]]; then
	source "$HOME/.local/lib/utils"
fi

if type -p export_proxy; then
	export_proxy >/dev/null 2>&1
fi

# Aliases
alias sqlite=sqlite3
alias chrome=google-chrome-stable
alias ytdl-video='yt-dlp -f "bv*[height<=720]+ba/b[height<=720]" --merge-output-format mkv'
alias ytdl-audio='yt-dlp -x --audio-format mp3 --audio-quality 0'
